## Preprocessing

In [11]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [12]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.

application_df = application_df.drop(['EIN'],1)
application_df.sample(10)

<ipython-input-12-11ad0c897e04>:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  application_df = application_df.drop(['EIN'],1)

,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
33672,DISABLED AMERICAN VETERANS,T4,CompanySponsored,C3000,Preservation,Association,1,0,N,5000,0
30716,AMERICAN ASSOCIATION OF UNIVERSITY WOMEN INC,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
20653,SOLID WASTE ASSOCIATION OF NORTH AMERICA INC,T3,CompanySponsored,C1200,Preservation,Trust,1,100000-499999,N,144729,0
10633,JAMESTOWN SOCIETY,T3,CompanySponsored,C1000,Preservation,Trust,1,0,N,5000,1
18952,LUNA WEST FOUNDATION - WOMEN REBUILDING WEALTH,T3,Independent,C1270,Preservation,Trust,1,0,N,5000,1
33380,NORTHERN CALIFORNIA CHAPTER OF THE SOCIETY OF ...,T3,Independent,C2000,Preservation,Trust,1,0,N,5000,1
30178,NATIONAL INSTITUTE OF GOVERNMENTAL PURCHASING INC,T3,CompanySponsored,C2800,Preservation,Association,1,100000-499999,N,105049,1
24682,PTA UTAH CONGRESS,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
17151,TOPS CLUB INC,T3,CompanySponsored,C1200,Preservation,Association,1,0,N,5000,0
1667,AMERICAN ASSOCIATION OF BLACKS IN ENERGY,T3,Independent,C1000,Preservation,Trust,1,25000-99999,N,32153,1

In [13]:
# Determine the number of unique values in each column.
application_df.nunique()

NAME                      19568
APPLICATION_TYPE             17
AFFILIATION                   6
CLASSIFICATION               71
USE_CASE                      5
ORGANIZATION                  4
STATUS                        2
INCOME_AMT                    9
SPECIAL_CONSIDERATIONS        2
ASK_AMT                    8747
IS_SUCCESSFUL                 2
dtype: int64

In [14]:
# Look at APPLICATION_TYPE value counts for binning

name_counts = application_df.NAME.value_counts()
name_counts

PARENT BOOSTER USA INC                                                  1260
TOPS CLUB INC                                                            765
UNITED STATES BOWLING CONGRESS INC                                       700
WASHINGTON STATE UNIVERSITY                                              492
AMATEUR ATHLETIC UNION OF THE UNITED STATES INC                          408
                                                                        ...
ST LOUIS SLAM WOMENS FOOTBALL                                              1
AIESEC ALUMNI IBEROAMERICA CORP                                            1
WEALLBLEEDRED ORG INC                                                      1
AMERICAN SOCIETY FOR STANDARDS IN MEDIUMSHIP & PSYCHICAL INVESTIGATI       1
WATERHOUSE CHARITABLE TR                                                   1
Name: NAME, Length: 19568, dtype: int64

In [15]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`

names_to_replace = list(name_counts[name_counts<=5].index)
names_to_replace

# Replace in dataframe
for app in names_to_replace:
    application_df['NAME'] = application_df['NAME'].replace(app,"Other")

# Check to make sure binning was successful
application_df['NAME'].value_counts()

Other                                           20043
PARENT BOOSTER USA INC                           1260
TOPS CLUB INC                                     765
UNITED STATES BOWLING CONGRESS INC                700
WASHINGTON STATE UNIVERSITY                       492
                                                ...
HABITAT FOR HUMANITY INTERNATIONAL                  6
DAMAGE PREVENTION COUNCIL OF TEXAS                  6
FLEET RESERVE ASSOCIATION                           6
HUGH OBRIAN YOUTH LEADERSHIP                        6
INTERNATIONAL CONGRESS OF CHURCHES MINISTERS        6
Name: NAME, Length: 355, dtype: int64

In [16]:
# Look at APPLICATION_TYPE value counts for binning

app_counts = application_df.APPLICATION_TYPE.value_counts()
app_counts

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [17]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`

application_types_to_replace = list(app_counts[app_counts<500].index)
application_types_to_replace

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [18]:
# Look at CLASSIFICATION value counts for binning
class_count_bin = application_df.CLASSIFICATION.value_counts()
class_count_bin

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [19]:
# You may find it helpful to look at CLASSIFICATION value counts >1

class_count_greater = class_count_bin[class_count_bin>1]
class_count_greater

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [20]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`

classifications_to_replace = list(class_count_bin[class_count_bin<1000].index)

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [21]:
# Convert categorical data to numeric with `pd.get_dummies`
application_df = pd.get_dummies(application_df)

In [22]:
# Split our preprocessed data into our features and target arrays

y = application_df['IS_SUCCESSFUL'].values

X = application_df.drop('IS_SUCCESSFUL',1).values

# Split the preprocessed data into a training and testing dataset

X_train, X_test, y_train, y_test = train_test_split(X,y,random_state = 1)

<ipython-input-22-56dc3d94ff15>:5: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  X = application_df.drop('IS_SUCCESSFUL',1).values

In [23]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [24]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
#X_train_scaled

number_of_input_features = len(X_train[0])

hidden_layer_1 = 80

hidden_layer_2 = 30

nn = tf.keras.models.Sequential()

# First hidden layer

nn.add(tf.keras.layers.Dense(units=hidden_layer_1, input_dim=number_of_input_features, activation="relu"))

# Second hidden layer

nn.add(tf.keras.layers.Dense(units=hidden_layer_2, input_dim=number_of_input_features, activation="relu"))

# Output layer

nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 80)                31920

 dense_1 (Dense)             (None, 30)                2430

 dense_2 (Dense)             (None, 1)                 31

=================================================================
Total params: 34381 (134.30 KB)
Trainable params: 34381 (134.30 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [25]:
# Compile the model

nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [26]:
# Train the model
nn.fit(X_train_scaled, y_train, epochs=100)

Epoch 1/100
804/804 [==============================] - 3s 2ms/step - loss: 0.4729 - accuracy: 0.7785
Epoch 2/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4342 - accuracy: 0.7924
Epoch 3/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4286 - accuracy: 0.7948
Epoch 4/100
804/804 [==============================] - 3s 3ms/step - loss: 0.4267 - accuracy: 0.7956
Epoch 5/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4250 - accuracy: 0.7974
Epoch 6/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4237 - accuracy: 0.7976
Epoch 7/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4221 - accuracy: 0.7974
Epoch 8/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4212 - accuracy: 0.7980
Epoch 9/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4200 - accuracy: 0.7994
Epoch 10/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4201 - accuracy: 0.7987
Epoch 11/100
804/804 [==============================] - 3s 3ms/step - loss: 0.4194 - accuracy: 0.7987
Epoch 12/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4180 - accuracy: 0.7998
Epoch 13/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4175 - accuracy: 0.8007
Epoch 14/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4172 - accuracy: 0.8011
Epoch 15/100
804/804 [==============================] - 3s 4ms/step - loss: 0.4165 - accuracy: 0.8013
Epoch 16/100
804/804 [==============================] - 6s 8ms/step - loss: 0.4163 - accuracy: 0.8004
Epoch 17/100
804/804 [==============================] - 5s 6ms/step - loss: 0.4161 - accuracy: 0.8018
Epoch 18/100
804/804 [==============================] - 5s 6ms/step - loss: 0.4157 - accuracy: 0.8027
Epoch 19/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4148 - accuracy: 0.8032
Epoch 20/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4145 - accuracy: 0.8019
Epoch 21/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4140 - accuracy: 0.8025
Epoch 22/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4135 - accuracy: 0.8025
Epoch 23/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4136 - accuracy: 0.8025
Epoch 24/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4128 - accuracy: 0.8041
Epoch 25/100
804/804 [==============================] - 3s 3ms/step - loss: 0.4126 - accuracy: 0.8034
Epoch 26/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4117 - accuracy: 0.8038
Epoch 27/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4120 - accuracy: 0.8042
Epoch 28/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4116 - accuracy: 0.8040
Epoch 29/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4112 - accuracy: 0.8036
Epoch 30/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4107 - accuracy: 0.8042
Epoch 31/100
804/804 [==============================] - 3s 3ms/step - loss: 0.4110 - accuracy: 0.8045
Epoch 32/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4106 - accuracy: 0.8043
Epoch 33/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4104 - accuracy: 0.8044
Epoch 34/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4100 - accuracy: 0.8038
Epoch 35/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4101 - accuracy: 0.8052
Epoch 36/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4093 - accuracy: 0.8052
Epoch 37/100
804/804 [==============================] - 3s 3ms/step - loss: 0.4092 - accuracy: 0.8052
Epoch 38/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4090 - accuracy: 0.8049
Epoch 39/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4088 - accuracy: 0.8043
Epoch 40/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4088 - accuracy: 0.8051
Epoch 41/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4087 - accuracy: 0.8054
Epoch 42/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4083 - accuracy: 0.8057
Epoch 43/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4083 - accuracy: 0.8050
Epoch 44/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4077 - accuracy: 0.8057
Epoch 45/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4076 - accuracy: 0.8062
Epoch 46/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4077 - accuracy: 0.8057
Epoch 47/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4077 - accuracy: 0.8059
Epoch 48/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4076 - accuracy: 0.8066
Epoch 49/100
804/804 [==============================] - 3s 3ms/step - loss: 0.4071 - accuracy: 0.8055
Epoch 50/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4071 - accuracy: 0.8061
Epoch 51/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4071 - accuracy: 0.8057
Epoch 52/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4069 - accuracy: 0.8060
Epoch 53/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4064 - accuracy: 0.8061
Epoch 54/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4062 - accuracy: 0.8060
Epoch 55/100
804/804 [==============================] - 3s 4ms/step - loss: 0.4065 - accuracy: 0.8059
Epoch 56/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4062 - accuracy: 0.8061
Epoch 57/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4059 - accuracy: 0.8063
Epoch 58/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4058 - accuracy: 0.8059
Epoch 59/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4061 - accuracy: 0.8062
Epoch 60/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4056 - accuracy: 0.8070
Epoch 61/100
804/804 [==============================] - 4s 5ms/step - loss: 0.4053 - accuracy: 0.8064
Epoch 62/100
804/804 [==============================] - 3s 3ms/step - loss: 0.4052 - accuracy: 0.8066
Epoch 63/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4052 - accuracy: 0.8062
Epoch 64/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4052 - accuracy: 0.8075
Epoch 65/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4051 - accuracy: 0.8063
Epoch 66/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4050 - accuracy: 0.8068
Epoch 67/100
804/804 [==============================] - 3s 4ms/step - loss: 0.4049 - accuracy: 0.8074
Epoch 68/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4044 - accuracy: 0.8068
Epoch 69/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4045 - accuracy: 0.8070
Epoch 70/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4042 - accuracy: 0.8076
Epoch 71/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4043 - accuracy: 0.8075
Epoch 72/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4040 - accuracy: 0.8070
Epoch 73/100
804/804 [==============================] - 3s 3ms/step - loss: 0.4039 - accuracy: 0.8069
Epoch 74/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4041 - accuracy: 0.8073
Epoch 75/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4037 - accuracy: 0.8076
Epoch 76/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4033 - accuracy: 0.8067
Epoch 77/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4038 - accuracy: 0.8068
Epoch 78/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4035 - accuracy: 0.8067
Epoch 79/100
804/804 [==============================] - 3s 4ms/step - loss: 0.4034 - accuracy: 0.8071
Epoch 80/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4031 - accuracy: 0.8064
Epoch 81/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4032 - accuracy: 0.8077
Epoch 82/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4040 - accuracy: 0.8080
Epoch 83/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4029 - accuracy: 0.8076
Epoch 84/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4030 - accuracy: 0.8083
Epoch 85/100
804/804 [==============================] - 3s 4ms/step - loss: 0.4031 - accuracy: 0.8076
Epoch 86/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4026 - accuracy: 0.8073
Epoch 87/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4025 - accuracy: 0.8077
Epoch 88/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4025 - accuracy: 0.8078
Epoch 89/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4030 - accuracy: 0.8081
Epoch 90/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4022 - accuracy: 0.8080
Epoch 91/100
804/804 [==============================] - 3s 4ms/step - loss: 0.4026 - accuracy: 0.8077
Epoch 92/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4029 - accuracy: 0.8078
Epoch 93/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4025 - accuracy: 0.8068
Epoch 94/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4025 - accuracy: 0.8065
Epoch 95/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4022 - accuracy: 0.8073
Epoch 96/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4023 - accuracy: 0.8078
Epoch 97/100
804/804 [==============================] - 3s 4ms/step - loss: 0.4021 - accuracy: 0.8075
Epoch 98/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4016 - accuracy: 0.8085
Epoch 99/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4023 - accuracy: 0.8068
Epoch 100/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4016 - accuracy: 0.8080

In [27]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.4749 - accuracy: 0.7923 - 557ms/epoch - 2ms/step
Loss: 0.47490498423576355, Accuracy: 0.792303204536438

In [ ]:
# Export our model to HDF5 file
nn.save("AlphabetSoupCharity_Optimization.h5")